In [55]:
class Person:
	def __init__(self, firstName, lastName, idNumber):
		self.firstName = firstName
		self.lastName = lastName
		self.idNumber = idNumber
	def printPerson(self):
		print("Name:", self.lastName + ",", self.firstName)
		print("ID:", self.idNumber)

class Student(Person):
    #   Class Constructor
    
    #   
    #   Parameters:
    #   firstName - A string denoting the Person's first name.
    #   lastName - A string denoting the Person's last name.
    #   id - An integer denoting the Person's ID number.
    #   scores - An array of integers denoting the Person's test scores.
    #
    # Write your constructor here
    def __init__(self,firstName,lastName,idNumber,score):
        self.firstName = firstName
        self.lastName = lastName
        self.idNumber = idNumber
        self.score=score
    def scores(self):
        print(self.score[0])
    def calculate(self):
        gr=sum(self.score)
        gr=gr/numScores
        if gr >=90 :
            return "O"
        elif gr >=80:
            return "E"
        elif gr >=70:
            return "A"
        elif gr >=55:
            return "P"
        elif gr >=40:
            return "D"
        else:
            return "T"
    

    #   Function Name: calculate
    #   Return: A character denoting the grade.
    #
    # Write your function here

line = input().split()
firstName = line[0]
lastName = line[1]
idNum = line[2]
numScores = int(input()) # not needed for Python
scores = list( map(int, input().split()) )
s = Student(firstName, lastName, idNum, scores)
s.printPerson()
print("Grade:", s.calculate())

ANUM JAW 12345
3
100 60 30
Name: JAW, ANUM
ID: 12345
Grade: P


In [7]:
class Person:
    def __init__(self,fname,lname,nid):
        self.fname=fname
        self.lname=lname
        self.nid=nid
    def pr(self):
        print("name",self.fname)
        print("lname",self.lname)        
        print("nid",self.nid)        

In [8]:
a=Person("ANUM","JA",1234)

In [9]:
a.pr()

name ANUM
lname JA
nid 1234


In [49]:
class Student(Person):
    def __init__(self,fname,lname,nid,score):
        self.fname=fname
        self.lname=lname
        self.nid=nid
        self.score=score
    def scores(self):
        print(self.score[0])
    def grade(self):
        gr=self.score[0]+self.score[1]
        gr=gr/numScores
        if gr >=90 :
            return "O"
        elif gr >=80:
            return "E"
        elif gr >=70:
            return "A"
        elif gr >=55:
            return "P"
        elif gr >=40:
            return "D"
        else:
            return "T"
    

In [50]:
b=Student("JAWAID","AN",12345,[100,80])

In [51]:
line = input().split()
firstName = line[0]
lastName = line[1]
idNum = line[2]
numScores = int(input()) # not needed for Python
scores = list( map(int, input().split()) )
s = Student(firstName, lastName, idNum, scores)
s.pr()
s.scores()
print("Grade:", s.grade())

ANUM JAW 123456
2
100 20 
name ANUM
lname JAW
nid 123456
100
Grade: P


In [54]:
sum(scores)

120

In [43]:
b.pr()
b.scores()
b.grade()

name JAWAID
lname AN
nid 12345
100
Grade:O


In [30]:
ar1[0][1][1:3]

array([5, 6])

In [31]:
ac=ar1[0].copy()
ac
anc=ar1[0]

In [33]:
ar1[0]=42


array([[42, 42, 42],
       [42, 42, 42]])

In [34]:
arr=np.array([ 0, 1, 2, 3, 4, 64, 64, 64, 8, 9])
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [36]:
arr2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[:,0:1]

array([[1],
       [4],
       [7]])

In [67]:
#arr2d[]
arr2d[[0,1,2]][:,[0,1,2]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [68]:
arr=np.arange(15).reshape(3,5)

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [52]:
score

NameError: name 'score' is not defined